name: Quality

on:
  push:
    paths:
    - "*"
    - "!README.md"
  pull_request:

jobs:
  golangci:
    name: GolangCI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GolangCI
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.31
